### ISSUE TITLE
Change in the styles to: height: Dimensions.get('screen').height

### ISSUE THREAD

**Issue by develad** [Savinvadim1312/TeslaClone#1]
Hello Vadim! 👋😃

I've watched the full tutorial and cloned the repo to my local machine and viewed it on my phone and saw the background picture doesn't fit the whole screen.
when I changed the property  'window' to 'screen' in the styles it fixed it.

Much respect to your work and videos,
keep up the good work!
Elad

**Comment by VadimNotJustDev** [comment]
Hey, thanks for the help. 
It will be useful for future devs to know what the problem was
